import Header from 'components/Header'
import Head from 'next/head'
import Image from 'next/image'
import {MagnifyingGlassIcon, MicrophoneIcon} from "@heroicons/react/24/solid";
import Body from 'components/Body';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Header*/}
      <Header/>
      {/*Body*/}
      <Body/>
      {/*Footer*/}
    </div>
  )
}
